// Turns tokens/tokens.json (exported from the Figma variables) into src/styles/tokens.css.
// Names stay Figma's: "text/primary" -> --text-primary, "space/16" -> --space-16.
// Never edit tokens.css by hand: change Figma, re-export tokens.json, run `npm run tokens`.
import { readFileSync, writeFileSync } from 'node:fs';

const doc = JSON.parse(readFileSync(new URL('../tokens/tokens.json', import.meta.url), 'utf8'));
const cssName = (n) => '--' + n.replaceAll('/', '-');
const lines = [];
const emit = (collection, unit) => {
  lines.push(`  /* ${collection} */`);
  for (const [name, t] of Object.entries(doc[collection])) {
    if (t.alias) lines.push(`  ${cssName(name)}: var(${cssName(t.alias)});`);
    else {
      const raw = String(t.value);
      const isNumber = /^-?\d+(\.\d+)?$/.test(raw);
      lines.push(`  ${cssName(name)}: ${isNumber && unit(name) ? raw + unit(name) : raw};`);
    }
  }
};
emit('Primitives', () => '');
emit('Color', () => '');
emit('Dimension', () => 'px');
emit('Motion', (n) => (n.includes('/duration/') ? 'ms' : ''));

const families = { Geist: "'Geist', system-ui, sans-serif", 'Geist Mono': "'Geist Mono', ui-monospace, monospace" };
const textVars = [];
const textClasses = [];
for (const [name, s] of Object.entries(doc.Text)) {
  const slug = name.toLowerCase().replaceAll('/', '-');
  textVars.push(`  --type-${slug}: ${s.weight} ${s.size}px/${s.lineHeight}px ${families[s.family]};`);
  textVars.push(`  --type-${slug}-tracking: ${s.letterSpacingPercent / 100}em;`);
  textClasses.push(
    `.t-${slug} { font: var(--type-${slug}); letter-spacing: var(--type-${slug}-tracking);${s.uppercase ? ' text-transform: uppercase;' : ''}${s.family === 'Geist Mono' ? ' font-variant-numeric: tabular-nums;' : ''} }`,
  );
}

const css = `/* Generated by scripts/export-tokens.mjs from tokens/tokens.json (${doc.$exported}). Do not edit. */
:root {
${lines.join('\n')}
  /* Text */
${textVars.join('\n')}
}

${textClasses.join('\n')}
`;
writeFileSync(new URL('../src/styles/tokens.css', import.meta.url), css);
console.log(`tokens.css: ${lines.length + textVars.length} custom properties, ${textClasses.length} text styles`);
